### ISSUE TITLE
Is it possible to get microsecond precision / NTP supports millisecond?

### ISSUE THREAD

**Issue by johndpope** [Apolotary/MultipeerNTP#1]
these methods below have microsecond precision. 
My current thought process is to send a message to peer - calculate round trip then work out how off it is. If the but which one to adjust... and then device -network delay can be variable.

```

uint64_t AECurrentTimeInHostTicks(void) {
    return mach_absolute_time();
}

double AECurrentTimeInSeconds(void) {
    if ( !__hostTicksToSeconds ) AETimeInit();
    return mach_absolute_time() * __hostTicksToSeconds;
}

uint64_t AEHostTicksFromSeconds(double seconds) {
    if ( !__secondsToHostTicks ) AETimeInit();
    assert(seconds >= 0);
    return seconds * __secondsToHostTicks;
}

double AESecondsFromHostTicks(uint64_t ticks) {
    if ( !__hostTicksToSeconds ) AETimeInit();
    return ticks * __hostTicksToSeconds;
}
```

**Comment by Apolotary** [comment]
Uh in which file is that? I might've been using whatever Pd/libpd had at the moment

**Comment by johndpope** [comment]
You know It’s probably not a big thing. That code is from amazing audio engine it’s able to get local precision on the same device. But I wonder if there’s a way to get phones to sync play sounds to microsecond. I have to experiment I noticed you had a metronome wav file in code base. Did you commercialise this? Or is there some code lying around to play sounds. I’m close to having something so will keep pushing ahead.

**Comment by Apolotary** [comment]
Whoa, sorry I totes forgot about it. Hope you figured out the issue eventually though
